### ISSUE TITLE
StackOverflowError when deleting large workspace

### ISSUE THREAD

**Issue by felixb** [flosell/lambdacd#112]
lambdacd runs into stackoverflow when deleting/closing a large workspace.

```
StackOverflowError 
	clojure.core/apply (core.clj:632)
	me.raynes.fs/file (fs.clj:56)
	me.raynes.fs/as-path (fs.clj:170)
	me.raynes.fs/directory? (fs.clj:205)
	clojure.core/apply (core.clj:632)
	me.raynes.fs/delete-dir (fs.clj:212)
	clojure.core/apply (core.clj:632)
	me.raynes.fs/delete-dir (fs.clj:214)
	clojure.core/apply (core.clj:632)
	me.raynes.fs/delete-dir (fs.clj:214)
	clojure.core/apply (core.clj:632)
	me.raynes.fs/delete-dir (fs.clj:214)
```

**Comment by flosell** [comment]
Hi, thanks for reporting this. I think the issue wasn't the size of the workspace but symlinks it contained: 

I reproduced the behavior with a deep directory structure with symlinks that led back to the start. Doesn't happen on OS X by the way, only on Linux. 

Let me know if this fixes your issue, otherwise feel free to reopen
