### ISSUE TITLE
How to combine a few projects in one lambdacd service?

### ISSUE THREAD

**Issue by cyrillk** [flosell/lambdacd#121]
Hi,

I really love the idea of lambdacd and currently trying to set it up for my projects.

Though I have not found any good example of how I can use lambdacd to build a few separate projects. I'd really appreciate your advise. Thank you.

**Comment by flosell** [comment]
Hi, 

having several projects in one LambdaCD service is absolutely supported, it's basically just starting multiple instances of LambdaCD within the same process. Here is an example of how this looks like: https://github.com/flosell/lambdacd-cookie-cutter-pipeline-example/

It's geared more towards having multiple pipelines with the same structure but the approach should be more or less the same if you have different structures. You set up your build steps and pipeline structures for every pipeline you have, call the start-up steps (the things typically in your `main` function) for every one of them and set up different routes for the different UIs. 

Hope this helps you, otherwise let me know. 

Cheers, 
Florian

**Comment by cyrillk** [comment]
Ok, I see now. I've not expected that I need to create a menu myself for it ) Thanks a lot for explaining it to me!

Minor question. When I run https://github.com/flosell/lambdacd-cookie-cutter-pipeline-example/ it says 
```
WARNING: alias already refers to: #'clojure.core/alias in namespace: pipeline-templates.pipeline, being replaced by: #'lambdacd.steps.control-flow/alias
``` 
in the logs. Is it something to worry about? How to avoid it? Sorry, I'm not very experienced with clojure.

**Comment by flosell** [comment]
Yes, the process of spinning up multiple pipelines (and creating a menu) is a bit more involved than I'd like it to be. I have this on the back of my head but don't have a good solution right now. I know some LambdaCD users have their own in-house solutions that are more opinionated, maybe they'll open-source this in the future. 

The warning is clojure telling you that you are importing the function `alias` from two different namespaces, the default `clojure.core` namespace and `lambdacd.steps.control-flow`. I didn't realize this naming conflict when creating the `alias` feature. It's nothing to worry about unless you want to use both functions at the same time. 

There are two ways to get rid of the warning: 
* Don't use `:use` or `:refer :all` for `lambdacd.steps.control-flow` (as this imports the content of this namespace directly into the current namespace). Use namespace aliasing or requiring individual functions instead 
* Prevent `clojure.core/alias` from being imported: `(:refer-clojure :exclude [alias])`

Here's a nice cheatsheet on the different ways to import things into the current namespace: https://gist.github.com/ghoseb/287710/

**Comment by cyrillk** [comment]
Thank you!

P.S. you can close the ticket now if you'd like.

**Comment by utkarshu91** [comment]
hi,
this is an amazing idea of converting the process of build and deploy pipeline into the code
i'm trying to set this up for my nodejs web application which needs to be build on a local machine and then deployed in a docker container but i'm kind of struggling in finding the proper documentation for these things to put to work.
And i also have a question that when i change home-dir in core.clj under
config {:home-dir home-dir
it gives me an error that invalid token 
i'd really appreciate if you could help me out with this.

**Comment by flosell** [comment]
@utkarshu91 looks like this question is a duplicate of #164
