### ISSUE TITLE
Git not switching branches

### ISSUE THREAD

**Issue by juanibiapina** [flosell/lambdacd#125]
I followed the exact tutorial here: http://www.lambda.cd/getting-started/

Except that I changed the repository and the branch. I also changed the command to run tests to "git status"

When triggering this pipeline manually, it always prints master, instead of the specified branch.

Is this a bug?

**Comment by flosell** [comment]
I'd say it's not a bug but a weakness of the example and maybe of LambdaCDs internal git implementation since it hides a few implicit assumptions: 

* `with-repo` expects a `:revision` information passed from the previous step (i.e. the trigger)
* `wait-for-repo` supplies this information, i.e. the revision of the new commit it found
* `wait-for-manual-trigger`, not knowing anything about git, doesn't supply this information
* if `with-repo` doesn't get a revision it falls back to the head of the master branch

For you, there are two ways to approach this problem: 

* supply a `:revision` from a manual trigger (wait-for-repo accepts revisions as well as branches): 
   ```clojure
   (defn trigger-manually [args ctx]
     (assoc (manualtrigger/wait-for-manual-trigger args ctx) :revision repo-branch))

  (def pipeline-def
  `(
     (either
       trigger-manually
       wait-for-repo)
     (with-repo
       run-some-tests)))
  ```
* have a look at [lambdacd-git](https://github.com/flosell/lambdacd-git). It's my approach to extract git functionality and makes some of the above things more explicit and more flexible to handle. This library is going to be the future anyway so it's worth checking it out. 

Does that help? 

For me, this is feedback that I need to clarify the getting started guide in this respect so thanks for letting me know!

**Comment by juanibiapina** [comment]
Thanks for the clarifications!
