### ISSUE TITLE
selfupdate solution

### ISSUE THREAD

**Issue by kwladyka** [flosell/lambdacd#152]
Hi,

Do you have some good solution to selfupdate lambdacd project on server? Just using jenkins for that will be a little irony :) I see a few options, but i guess somebody already did it :)

PS i created #lambdacd on clojurians slack. Maybe it is worth to add place like that in readme for people to share experience.

**Comment by flosell** [comment]
Self-Update as in "I want to deploy changes in the pipeline? What lots of people do is deploy a LambdaCD instance that contains more than one pipeline, one of them the pipeline that deploys the LambdaCD instance itself. 

Thanks for the suggestion of a slack channel. I set up a gitter-channel a while ago (that's also linked in the readme) but it hasn't received too much traffic yet (plus it apparently doesn't notify me). I'm open to try out slack, and added it to the readme. Maybe that'll receive a bit more attention. :)

**Comment by flosell** [comment]
@kwladyka Is this question resolved?

**Comment by kwladyka** [comment]
Not yet. When i will find solution with devops i can share it here.

**Comment by kwladyka** [comment]
Did you find any solution for that? I didn't.

**Comment by flosell** [comment]
As mentioned before, most people I know just have several pipelines in a single LambdaCD process, one of them being a "meta"-pipeline that deploys LambdaCD itself. You'll also find some thoughts on this [here](https://github.com/flosell/lambdacd/blob/master/doc/howto.md#how-do-i-deploy-my-pipeline).

There are of course a few other possible ideas, e.g. on running a process that can "load" pipeline-code dynamically. But since this would be quite a fundamental shift in philosophy don't expect this to be implemented in the immediate future. Community contributions are always encouraged though ;) 

Closing this issue for now.
