### ISSUE TITLE
Retriggering jobs leaves the pipeline list somewhat counterintuitive

### ISSUE THREAD

**Issue by redvox** [flosell/lambdacd#27]
So you start with Build 1, after step is a success (if you use the after-first-step runner), a new pipeline (Build 2) is spawned.
Build 1 has an error and you retrigger a step, it will then be continued in a new pipeline named Build 3.
When you want to start a new the pipeline, you have to take Build 2, because its the only available.

If you retrigger, it is hard to figure out which was the last run and which rerun belongs to which pipeline. Especially if you have multiple pipelines running at the same time.

My proposal would be to have something like versions of a pipeline run.
You have Build 1 running, Build 2 is spawned.
You have to retrigger something in Build 1, so it will be continued in Build 1.1.
If you have to retrigger it again, it will be continued in Build 1.2.

This way you can see quickly which pipeline runs belong together.

**Comment by flosell** [comment]
Interesting idea, I'll see what I can do

**Comment by flosell** [comment]
Since 0.5.5, the build history shows a bit more detail e.g. when a build was started and which build was retriggered: 

![image](https://cloud.githubusercontent.com/assets/540525/10417446/45c1d0bc-703c-11e5-988c-8e8aee1275df.png)

What do you think? Does this help understanding which build is which? Does this resolve the issue?

**Comment by alphaone** [comment]
:+1:

**Comment by flosell** [comment]
closing this for now, feel free to reopen if there's still a need for more improvements
