### ISSUE TITLE
Add init-state-fn parameter to assemble-pipeline

### ISSUE THREAD

**Issue by SimonMonecke** [flosell/lambdacd#40]
If I want to use another init-pipeline-state function I must copy&paste the function assemble-pipeline.
I would make it more generic with an additional parameter.

```clojure
(defn assemble-pipeline
  ([pipeline-def config]
   (assemble-pipeline pipeline-def config initialize-default-pipeline-state))
  ([pipeline-def config init-state-fn]
  (let [context (-> {:config                   config
                    :step-results-channel     (async/chan (async/dropping-buffer 100))}
                    (event-bus/initialize-event-bus)
                    (init-state-fn))]
                    ...
```
I need another init function in [lambdacd-rest](https://github.com/SimonMonecke/lambdacd-rest) and so I can get rid of one copied function

**Comment by flosell** [comment]
Hi Simon, 

thanks for the feedback!
I'm not completely happy with how bootstrapping works in general and `assemble-pipeline` is one of the aspects I want to look at. 

To address your immediate issue, passing in the init function would be an option, but I think we can make this even simpler: 

Since version 0.4.3, all access to the internal state of the pipeline component is deprecated and I'll remove what remained for compatibility now. Then, we could just pass in a fully initialized instance of `PipelineStateComponent`. 

What do you think?

**Comment by flosell** [comment]
ok, after refactoring the code for a bit, I think I get why you wanted the function: you needed a more or less complete `ctx` with a fully initialized event bus before you could even initialized the component so that `start-pipeline-state-updater` works. 

I've made `start-pipeline-state-updater` generic so that it is initialized in `assemble-pipeline` and state components don't need to worry about it, making state components more independent. 

You should now be able to initialize any state component and drop it into `assemble-pipeline`: 

```clojure
(defn assemble-pipeline
  ([pipeline-def config]
   (assemble-pipeline pipeline-def config (default-pipeline-state/new-default-pipeline-state config)))
  ([pipeline-def config pipeline-state-component]
    (let [context (-> {:config                   config
                       :step-results-channel     (async/chan (async/dropping-buffer 100))}
                      (event-bus/initialize-event-bus)
                      (assoc :pipeline-state-component pipeline-state-component))]
      (pipeline-state/start-pipeline-state-updater (:pipeline-state-component context) context)
      {:context      context
       :pipeline-def pipeline-def})))
```

Does this work for you?

**Comment by SimonMonecke** [comment]
I just tried it and your solution works like a charm.

```clojure
pipeline (lambdacd/assemble-pipeline pipeline-def config (rest-state/new-rest-state config))
```
```clojure
(defn new-rest-state [config]
  (let [rest-cfg (:rest-cfg config)
        [...]
        state-atom (atom (initial-pipeline-state max-builds base-url))
        instance   (->RESTState state-atom base-url pipeline-def gid pid)]
    instance))
```

This code is included in [LambdaCD-REST](https://github.com/SimonMonecke/lambdacd-rest), version 0.3.3-SNAPSHOT.

I don't like the "config" parameter which appears twice in one line. We can mix our ideas:

```clojure
(defn assemble-pipeline
  ([pipeline-def config]
   (assemble-pipeline pipeline-def config default-pipeline-state/new-default-pipeline-state))
  ([pipeline-def config pipeline-state-component]
    (let [context (-> {:config                   config
                       :step-results-channel     (async/chan (async/dropping-buffer 100))}
                      (event-bus/initialize-event-bus)
                      (assoc :pipeline-state-component (pipeline-state-component config)))]
      (pipeline-state/start-pipeline-state-updater (:pipeline-state-component context) context)
      {:context      context
       :pipeline-def pipeline-def})))
```
Without additional parameters:
```clojure
pipeline (lambdacd/assemble-pipeline pipeline-def config rest-state/new-rest-state)
```
If you need additional parameters:
```clojure
pipeline (lambdacd/assemble-pipeline pipeline-def config (partial rest-state/new-rest-state extra-parms))
```

Which version is better? It's up to you!

**Comment by flosell** [comment]
Thanks for the feedback! 

I agree, having config twice in the same line might look a bit ugly. Your proposal on the other hand would make the interface more rigid: It expects that you always get the pipeline-component from a function that declares at least the config parameter. 

Unless you have major doubts on this, I'd prefer to keep the interface flexible for the user and stick with the slight duplication.
