### ISSUE TITLE
UI does not work after updating Firefox to version 0.41 (Xubuntu)

### ISSUE THREAD

**Issue by SimonMonecke** [flosell/lambdacd#57]
After updating Firefox to version 0.41 the UI hangs and only displays the message "Loading..."

OS: Xubuntu 15.04
Kernel: 3.19.0-28-generic x86_64 GNU/Linux

![bildschirmfoto_2015-09-23_16-10-28](https://cloud.githubusercontent.com/assets/4587790/10047262/a6562d2a-620d-11e5-8d69-efb855dead6c.png)

Console log:
```
TypeError: h is null
```

On a second PC with the same Firefox version I get the following error message:
```
TypeError: e is null
```
I did not installed any plugin in the browser.

**Comment by flosell** [comment]
Thanks for finding this! I'm personally not using firefox day to day so it's great to receive these reports!
 
I tried duplicating this and saw issues in firefox 41 as well. My best guess so far is they are connected to this breaking change in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1138325

Upgrading to the most recent version of clojurescript seems to resolve the issue so that's what I'm going to do. 
I haven't upgraded them in some while so a few issues have popped up trying to jump to the most recent versions. I'll sort those out and you can expect a fixed version soon. 

In the meantime, Chrome should work :)

**Comment by flosell** [comment]
just released `0.5.4` includes a fix so give this a try. and note that this release requires clojure 1.7

**Comment by SimonMonecke** [comment]
We still have the same error after updating to lambdacd 0.5.4 and clojure 1.7.0
