### ISSUE TITLE
Getting started guide leads to no main namespace exception

### ISSUE THREAD

**Issue by k0pernikus** [flosell/lambdacd#75]
I want to follow the [getting-started guide](http://www.lambda.cd/getting-started/) guide:

```
$ lein new lambdacd my-first-pipeline
Generating fresh 'lein new' lambdacd project.
$ cd my-first-pipeline
```

Yet instead for `lein run` to start the server, I get:

```
No :main namespace specified in project.clj.
```

I am on Ubuntu 14.04 and have I installed leininingen via package-manager and I have:
```
Leiningen 1.7.1 on Java 1.7.0_91 OpenJDK 64-Bit Server VM
```

What am I missing?

**Comment by flosell** [comment]
Hi, 

Leiningen 1.7.1 is fairly old and the templating mechanism has changed since then so using the latest Leiningen (2.5.3) might help:
Download the `lein` script from http://leiningen.org/, make it executable and call it instead of your installed version. 

I have also seen Leiningen not pulling the most recent template if an older one is already in the local maven cache. So if a newer Leiningen version doesn't work, try deleting `lambdacd/lein-template` from the maven cache. The folder should be `~/.m2/repository/lambdacd/lein-template` on most installations. 

As a side note, people have reported issues when running LambdaCD on JDK 1.7 (#62) so in case you experience any crashes later on, JDK 1.8 should fix those.

**Comment by flosell** [comment]
@k0pernikus is this still an issue?

**Comment by flosell** [comment]
closing for now, feel free to reopen if this is still an issue
